### ISSUE TITLE
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create' collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by hcp6897** [YeeCY/SMPLpp#4]
**Question:** I have encountered the error when compiling the project by cmake tools.
Run Build Command:"/usr/bin/make" "cmTC_c29db/fast"
/usr/bin/make -f CMakeFiles/cmTC_c29db.dir/build.make CMakeFiles/cmTC_c29db.dir/build
make[1]: Entering directory '/home/ubuntu/Downloads/SMPLpp-master/SMPL++/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c29db.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_c29db.dir/CheckSymbolExists.c.o   -c /home/ubuntu/Downloads/SMPLpp-master/SMPL++/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_c29db
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c29db.dir/link.txt --verbose=1
/usr/bin/cc      CMakeFiles/cmTC_c29db.dir/CheckSymbolExists.c.o  -o cmTC_c29db 
CMakeFiles/cmTC_c29db.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_c29db.dir/build.make:97: recipe for target 'cmTC_c29db' failed
make[1]: *** [cmTC_c29db] Error 1
make[1]: Leaving directory '/home/ubuntu/Downloads/SMPLpp-master/SMPL++/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_c29db/fast' failed
make: *** [cmTC_c29db/fast] Error 2

File /home/ubuntu/Downloads/SMPLpp-master/SMPL++/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/ubuntu/Downloads/SMPLpp-master/SMPL++/build/CMakeFiles/CMakeTmp

**Comment by YeeCY** [comment]
Which version of CMAKE did you use? I recommend using a newer version of CMAKE instead of the apt-get one.

**Comment by hcp6897** [comment]
Thanks, I have used the  cmake version 3.14.6


> Which version of CMAKE did you use? I recommend using a newer version of CMAKE instead of the apt-get one.

Thanks YeeCY !!  I have used the cmake version 3.14.6.

**Comment by YeeCY** [comment]
Did you solve the problem with version 3.14.6? I think we may close the issue now.

**Comment by hcp6897** [comment]
> Did you solve the problem with version 3.14.6? I think we may close the issue now.
This error always don't resolved, though I used the newest cmake-3.14.6.

**Comment by YeeCY** [comment]
It seems CMAKE can't find the pthread library. You can try to add it to the CMakeLists.txt manually. Let me know if you still have the problem.

**Comment by hcp6897** [comment]
This situation happened  when  I  have added the pthread library to the CMakeLists.txt manually before asked the question.

**Comment by YeeCY** [comment]
I can only figure out that CMAKE failed to link pthread on your machine. I found these links on google, and you can have a look.

https://stackoverflow.com/questions/1662909/undefined-reference-to-pthread-create-in-linux

https://github.com/DecodeGenetics/graphtyper/issues/9

**Comment by hcp6897** [comment]
> I can only figure out that CMAKE failed to link pthread on your machine. I found these links on google, and you can have a look.
> 
> I remodify the CMakeLists.txt by add "**set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wall")**" && "**add_compile_options(-pthread)**" to it. And I have continue to cmake sources within build folder. However, it also throws another problem in the following:
 "-- Configuring done
CMake Error at CMakeLists.txt:125 (add_executable):
  No SOURCES given to target: smplpp
". Why?
