### ISSUE TITLE
What is the speed of smplpp？

### ISSUE THREAD

**Issue by alanpeng1204** [YeeCY/SMPLpp#6]
I have run the smplpp on windows platform with vs2019. And the smplpp takes 20ms for a new pose on my notebook.
However, when I tested the official python code on windows with python2.7, they spent less than 10s for a new pose.
Could you please tell me the performance on your side？ Either Linux or Windows. Thanks.

**Comment by YeeCY** [comment]
Thanks for reporting the performance! I'm confused about the official 10s, did you actually mean 10ms? By the way, my GTX960M could run the code around 5ms - 10ms per pose on Ubuntu 18.04.

**Comment by alanpeng1204** [comment]
Sorry for the typo. Yes, I meant less than 10ms with official python code. 
My notebook is Surface book2 with GTX1050. 
Thank you very much for telling me about the performance on Ubuntu. It is really helpful.

**Comment by YeeCY** [comment]
As you can see, I didn't follow the official python code strictly but coded the formulations from scratch. The performance may be suboptimal by the way. If you have any questions about the performance, feel free to reopen the issue.
