### ISSUE TITLE
error: ‘has_trivial_default_constructor’ in namespace ‘std’ does not name a template type

### ISSUE THREAD

**Issue by newyun1979** [YeeCY/SMPLpp#7]
:
/usr/local/include/xtensor/xutils.hpp:629:51: error: ‘has_trivial_default_constructor’ in namespace ‘std’ does not name a template type
     using xtrivially_default_constructible = std::has_trivial_default_constructor<T>;

**Comment by YeeCY** [comment]
Close for inactivity
