### ISSUE TITLE
which gcc version do you use,I complied print so many error

### ISSUE THREAD

**Issue by newyun1979** [YeeCY/SMPLpp#8]
like this 
/home/a/smplc++/SMPLpp-master/include/toolbox/Exception.h:50:35: note: in definition of macro ‘smpl_error’
 #define smpl_error(module, error) Exception(module, error, \
                                   ^~~~~~~~~
/home/a/smplc++/SMPLpp-master/include/toolbox/Exception.h:154:5: note:   initializing argument 4 of ‘xt::smpl::Exception::Exception(int, int, int, int, int)’
     Exception(const std::string module, const std::string error,
     ^~~~~~~~~
/home/a/smplc++/SMPLpp-master/include/toolbox/Exception.h:50:35: error: invalid conversion from ‘const char*’ to ‘int’ [-fpermissive]
 #define smpl_error(module, error) Exception(module, error, \
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
     __func__, __FILE__, __LINE__)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
/home/a/smplc++/SMPLpp-master/include/toolbox/Exception.h:50:35: note: in definition of macro ‘smpl_error’
 #define smpl_error(module, error) Exception(module, error, \
                                   ^~~~~~~~~
/home/a/smplc++/SMPLpp-master/include/toolbox/Exception.h:154:5: note:   initializing argument 1 of ‘xt::smpl::Exception::Exception(int, int, int, int, int)’
     Exception(const std::string module, const std::string error,
     ^~~~~~~~~
/home/a/smplc++/SMPLpp-master/include/toolbox/Exception.h:50:35: error: invalid conversion from ‘const char*’ to ‘int’ [-fpermissive]
 #define smpl_error(module, error) Exception(module, error, \
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
     __func__, __FILE__, __LINE__)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
/home/a/smplc++/SMPLpp-master/include/toolbox/Exception.h:50:35: note: in definition of macro ‘smpl_error’
 #define smpl_error(module, error) Exception(module, error, \
                                   ^~~~~~~~~

**Comment by newyun1979** [comment]
sorry.I renew download the code,it worked, but I use libtorch 1.0.1

/usr/local/include/torch/csrc/api/include/torch/nn/modules/functional.h:63:36: error: expected ‘)’ before ‘function’
   explicit FunctionalImpl(Function function);
                                    ^~~~~~~~
/usr/local/include/torch/csrc/api/include/torch/nn/modules/functional.h:68:25: error: ‘enable_if_t’ in namespace ‘xt::torch’ does not name a template type
       typename = torch::enable_if_t<(sizeof...(Args) > 0)>>
                         ^~~~~~~~~~~
/usr/local/include/torch/csrc/api/include/torch/nn/modules/functional.h:68:36: error: expected ‘>’ before ‘<’ token
       typename = torch::enable_if_t<(sizeof...(Args) > 0)>>
                                    ^
/usr/local/include/torch/csrc/api/include/torch/nn/modules/functional.h:89:3: error: ‘Function’ does not name a type; did you mean ‘union’?
   Function function_;
   ^~~~~~~~
   union

**Comment by YeeCY** [comment]
Do you solve the problem?

**Comment by YeeCY** [comment]
Close for inactivity
